# Generated by Django 4.1.3 on 2023-01-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.CharField(default='', max_length=4)),
                ('end_date', models.CharField(max_length=4)),
                ('missions', models.TextField(max_length=1000)),
                ('location', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PersoInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=64)),
                ('website', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=64)),
                ('linkedin', models.CharField(max_length=128)),
                ('github', models.CharField(max_length=128)),
                ('numberphone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=128)),
                ('information', models.TextField(max_length=1024)),
                ('hobbies', models.TextField(max_length=1024)),
                ('file_cv', models.FileField(blank=True, upload_to='resume')),
            ],
            options={
                'verbose_name': 'Personnal information',
                'verbose_name_plural': 'Personnal information',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1', 'little'), ('2', 'good'), ('3', 'Excellent')], default='1', max_length=32)),
            ],
        ),
    ]
