name: Build Docker Image and Push to registry

on:
  push:
    branches:
      - 'master'
      - 'fist-dev'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hmei28/portfolio
          flavor: latest=true
          tags: |
            type=sha,event=branch
            type=semver,pattern={{version}}

      - name: Login to to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}